spring:
  config:
    activate:
      on-profile: azure

azure:
  speech:
    key: ${AZURE_SPEECH_KEY}
    region: ${AZURE_SPEECH_REGION}
    tts-endpoint: https://${AZURE_SPEECH_REGION}.tts.speech.microsoft.com
    stt-endpoint: https://${AZURE_SPEECH_REGION}.stt.speech.microsoft.com